spring.rabbitmq:
  host: rabbitmq
  port: 5672
  username: guest
  password: guest
management:
  influx:
    metrics:
      export:
        uri: http://localhost:8086
        step: 10s
        bucket: 6b876e0b46330b27
        org: rabbitorg
        token: 1_dvjkJb_oYeZpRS2l75xyAL6lk-gg_RdNSntmitYm4WfK9r8OFxn2TKjAQ_gG7zaKICQeBv2wR4oXoHjE02BA==
        api-version: v2
