version: "2.1"

services:
  activemq:
    image: webcenter/activemq:5.14.3
    ports:
      # mqtt
      - "1883:1883"
      # amqp
      - "5672:5672"
      # ui
      - "8161:8161"
      # stomp
      - "61613:61613"
      # ws
      - "61614:61614"
      # jms
      - "61616:61616"
    volumes: ["activemq-data:/opt/activemq/conf", "activemq-data:/data/activemq", "activemq-data:/var/log/activemq"]
    environment:
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: "true"
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: password
      ACTIVEMQ_WRITE_LOGIN: write
      ACTIVEMQ_WRITE_PASSWORD: password
      ACTIVEMQ_READ_LOGIN: read
      ACTIVEMQ_READ_PASSWORD: password
      ACTIVEMQ_JMX_LOGIN: jmx
      ACTIVEMQ_JMX_PASSWORD: password
      ACTIVEMQ_STATIC_TOPICS: static-topic-1;static-topic-2
      ACTIVEMQ_STATIC_QUEUES: static-queue-1;static-queue-2
      ACTIVEMQ_ENABLED_SCHEDULER: "true"
      ACTIVEMQ_MIN_MEMORY: 512
      ACTIVEMQ_MAX_MEMORY: 2048


  influxdb_jms:
    image: influxdb
    volumes:
      - influxdb_jms:/var/lib/influxdb_jms
    ports:
      - "8086:8086"

  chronograf_jms:
      image: chronograf
      volumes:
        - chronograf_jms:/var/lib/chronograf_jms
      ports:
        - "8888:8888"
      environment:
        INFLUXDB_HOST: influxdb_jms
        INFLUXDB_AUTH_TYPE: oauth2
        INFLUXDB_URL: http://influxdb_jms:8086
        INFLUXDB_TOKEN: G9HeO9kvKQSI3S1EeQCDb1X9N3IFU6vFC9zKVGauLFadLepYAKE7VOZZFHt4F-NKkvVKYR3cMY89o48GTTtIiw==
      command: --influxdb-url=http://influxdb_jms:8086
  telegraf_jms:
    image: telegraf
    container_name: telegraf_jms
    restart: always
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb_jms
      - activemq
    links:
      - influxdb_jms
      - activemq
    ports:
      - '8125:8125'

volumes:
  influxdb_jms:
  grafana_jms:
  chronograf_jms:
  activemq-data: {}