version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.7-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq_network
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq



  rabbitapp:
    image: rabbitapp
    container_name: 'rabbitapp'
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - rabbitmq_network
    links:
      - rabbitmq
    ports:
      - "8080:8080"
    environment:
      - spring_rabbitmq_host=rabbitmq
      - spring_rabbitmq_port=5672
      - spring_rabbitmq_username=guest
      - spring_rabbitmq_password=guest
networks:
  rabbitmq_network:




