version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.7-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq_network
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq



  rabbitapp:
    image: rabbitapp
    container_name: 'rabbitapp'
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - rabbitmq_network
    links:
      - rabbitmq
    ports:
      - "8080:8080"
    environment:
      - spring_rabbitmq_host=rabbitmq
      - spring_rabbitmq_port=5672
      - spring_rabbitmq_username=guest
      - spring_rabbitmq_password=guest

  influxdb_rabbit:
    image: influxdb
    volumes:
      - influxdb_rabbit:/var/lib/influxdb_rabbit
    networks:
      - rabbitmq_network
    ports:
      - "8086:8086"

  chronograf_rabbit:
      image: chronograf
      volumes:
        - chronograf_rabbit:/var/lib/chronograf_rabbit
      ports:
        - "8888:8888"
      networks:
        - rabbitmq_network
      environment:
        INFLUXDB_HOST: influxdb_rabbit
        INFLUXDB_AUTH_TYPE: oauth2
        INFLUXDB_URL: http://influxdb_rabbit:8086
        INFLUXDB_TOKEN: 1_dvjkJb_oYeZpRS2l75xyAL6lk-gg_RdNSntmitYm4WfK9r8OFxn2TKjAQ_gG7zaKICQeBv2wR4oXoHjE02BA==
      command: --influxdb-url=http://influxdb:8086
  telegraf_rabbit:
    image: telegraf
    container_name: telegraf_rabbit
    restart: always
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - rabbitmq_network
    depends_on:
      - influxdb_rabbit
      - rabbitmq
    links:
      - influxdb_rabbit
      - rabbitmq
    ports:
      - '8125:8125'

volumes:
    influxdb_rabbit:
    grafana_rabbit:
    chronograf_rabbit:

networks:
  rabbitmq_network:




